language: julia
os:
  - linux

julia:
  - 0.7

notifications:
  email: false

git:
  depth: 99999999

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://$GITHUB_TOKEN:github.com/$GITHUB_USER/Manopt.jl")); Pkg.build("Manopt"); Pkg.test("Manopt", coverage=true)';

after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("MathOptInterface")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Manopt")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
