language: julia

julia:
  - release

branches:
  only:
    - master

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ManifoldValuedImageProcessing"); Pkg.test("ManifoldvaluedImageProcessing"; coverage=true)'
