site_name:           Manopt.jl
repo_url:            https://github.com/kellertuer/Manopt.jl
site_description:    Optimization on Manifolds in Julia
site_author:         Ronny Bergmann
theme:               bootstrap

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
#  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Manifolds:
  - Introduction: manifolds/index.md
  - The Mtrix manifold: manifolds/matrixmanifold.md
  - The Sphere $\mathbb S^n$: manifolds/sphere.md
